import type { UiDocument } from "./ui-document.types";

const homeSurface: UiDocument = {
  id: "home-surface",
  name: "Home Surface",
  description: "Example-app inspired member workspace composition.",
  rootId: "home-root",
  stateLayouts: {
    data: ["home-nav", "home-hero", "home-list", "home-action-row"],
    loading: ["home-nav", "home-skeleton"],
    empty: ["home-nav", "home-hero", "home-empty", "home-action-row"],
    error: ["home-nav", "home-status", "home-action-row"],
  },
  nodes: {
    "home-root": { id: "home-root", type: "YStack", props: { gap: "$3", bg: "$bg", p: "$3" }, children: ["home-nav", "home-hero", "home-list", "home-action-row"] },
    "home-nav": { id: "home-nav", parentId: "home-root", type: "View", props: { bg: "$surfaceAlt", borderColor: "$borderSubtle", borderWidth: 1, br: "$3", px: "$3", py: "$3" }, children: ["home-nav-row"] },
    "home-nav-row": { id: "home-nav-row", parentId: "home-nav", type: "XStack", props: { ai: "center", gap: "$2" }, children: ["home-nav-icon", "home-nav-title", "home-nav-tag"] },
    "home-nav-icon": { id: "home-nav-icon", parentId: "home-nav-row", type: "Icon", props: { icon: "flask", tone: "info", size: "md" }, children: [] },
    "home-nav-title": { id: "home-nav-title", parentId: "home-nav-row", type: "Body", props: { text: "Example App", fontFamily: "$bold" }, children: [] },
    "home-nav-tag": { id: "home-nav-tag", parentId: "home-nav-row", type: "Tag", props: { label: "session ready", tone: "success" }, children: [] },
    "home-hero": { id: "home-hero", parentId: "home-root", type: "View", props: { bg: "$surfaceStrong", borderColor: "$borderSubtle", borderWidth: 1, br: "$3", p: "$4" }, children: ["home-hero-copy"] },
    "home-hero-copy": { id: "home-hero-copy", parentId: "home-hero", type: "YStack", props: { gap: "$1" }, children: ["home-hero-label", "home-hero-title", "home-hero-body"] },
    "home-hero-label": { id: "home-hero-label", parentId: "home-hero-copy", type: "Label", props: { text: "dashboard", color: "$textMuted", tt: "uppercase", letterSpacing: 1 }, children: [] },
    "home-hero-title": { id: "home-hero-title", parentId: "home-hero-copy", type: "Heading", props: { text: "Welcome back" }, children: [] },
    "home-hero-body": { id: "home-hero-body", parentId: "home-hero-copy", type: "Body", props: { text: "Shared backend, auth, and settings surfaces already wired together.", color: "$textMuted" }, children: [] },
    "home-list": { id: "home-list", parentId: "home-root", type: "View", props: { bg: "$surface", borderColor: "$borderSubtle", borderWidth: 1, br: "$3" }, children: ["home-list-stack"] },
    "home-list-stack": { id: "home-list-stack", parentId: "home-list", type: "YStack", props: {}, children: ["home-row-1", "home-row-2", "home-row-3"] },
    "home-row-1": { id: "home-row-1", parentId: "home-list-stack", type: "XStack", props: { ai: "center", gap: "$3", px: "$3", py: "$3" }, children: ["home-row-1-icon", "home-row-1-copy", "home-row-1-value"] },
    "home-row-1-icon": { id: "home-row-1-icon", parentId: "home-row-1", type: "Icon", props: { icon: "home", tone: "info", size: "sm" }, children: [] },
    "home-row-1-copy": { id: "home-row-1-copy", parentId: "home-row-1", type: "YStack", props: { gap: "$1" }, children: ["home-row-1-title", "home-row-1-sub"] },
    "home-row-1-title": { id: "home-row-1-title", parentId: "home-row-1-copy", type: "Body", props: { text: "Current session", fontFamily: "$bold" }, children: [] },
    "home-row-1-sub": { id: "home-row-1-sub", parentId: "home-row-1-copy", type: "Body", props: { text: "identity, onboarding, entitlements", color: "$textMuted", fontSize: "$1" }, children: [] },
    "home-row-1-value": { id: "home-row-1-value", parentId: "home-row-1", type: "Tag", props: { label: "ready", tone: "info" }, children: [] },
    "home-row-2": { id: "home-row-2", parentId: "home-list-stack", type: "XStack", props: { ai: "center", gap: "$3", px: "$3", py: "$3" }, children: ["home-row-2-icon", "home-row-2-copy", "home-row-2-value"] },
    "home-row-2-icon": { id: "home-row-2-icon", parentId: "home-row-2", type: "Icon", props: { icon: "table", tone: "info", size: "sm" }, children: [] },
    "home-row-2-copy": { id: "home-row-2-copy", parentId: "home-row-2", type: "YStack", props: { gap: "$1" }, children: ["home-row-2-title", "home-row-2-sub"] },
    "home-row-2-title": { id: "home-row-2-title", parentId: "home-row-2-copy", type: "Body", props: { text: "Shared backend", fontFamily: "$bold" }, children: [] },
    "home-row-2-sub": { id: "home-row-2-sub", parentId: "home-row-2-copy", type: "Body", props: { text: "generated routes and client plumbing", color: "$textMuted", fontSize: "$1" }, children: [] },
    "home-row-2-value": { id: "home-row-2-value", parentId: "home-row-2", type: "Tag", props: { label: "online", tone: "success" }, children: [] },
    "home-row-3": { id: "home-row-3", parentId: "home-list-stack", type: "XStack", props: { ai: "center", gap: "$3", px: "$3", py: "$3" }, children: ["home-row-3-icon", "home-row-3-copy", "home-row-3-value"] },
    "home-row-3-icon": { id: "home-row-3-icon", parentId: "home-row-3", type: "Icon", props: { icon: "user", tone: "info", size: "sm" }, children: [] },
    "home-row-3-copy": { id: "home-row-3-copy", parentId: "home-row-3", type: "YStack", props: { gap: "$1" }, children: ["home-row-3-title", "home-row-3-sub"] },
    "home-row-3-title": { id: "home-row-3-title", parentId: "home-row-3-copy", type: "Body", props: { text: "Profile access", fontFamily: "$bold" }, children: [] },
    "home-row-3-sub": { id: "home-row-3-sub", parentId: "home-row-3-copy", type: "Body", props: { text: "shared account and settings surfaces", color: "$textMuted", fontSize: "$1" }, children: [] },
    "home-row-3-value": { id: "home-row-3-value", parentId: "home-row-3", type: "Tag", props: { label: "open", tone: "warning" }, children: [] },
    "home-action-row": { id: "home-action-row", parentId: "home-root", type: "XStack", props: { gap: "$3", ai: "center" }, children: ["home-primary-action", "home-secondary-action"] },
    "home-primary-action": { id: "home-primary-action", parentId: "home-action-row", type: "Button", props: { text: "Refresh session", bg: "$primary" }, children: [] },
    "home-secondary-action": { id: "home-secondary-action", parentId: "home-action-row", type: "Button", props: { text: "Profile", bg: "$surfaceAlt", borderColor: "$border", borderWidth: 1 }, children: [] },
    "home-skeleton": { id: "home-skeleton", parentId: "home-root", type: "YStack", props: { gap: "$2", bg: "$surface", borderColor: "$borderSubtle", borderWidth: 1, br: "$3", p: "$3" }, children: ["home-skeleton-1", "home-skeleton-2", "home-skeleton-3"] },
    "home-skeleton-1": { id: "home-skeleton-1", parentId: "home-skeleton", type: "View", props: { bg: "$surfaceAlt", h: 14, w: "56%", br: "$2" }, children: [] },
    "home-skeleton-2": { id: "home-skeleton-2", parentId: "home-skeleton", type: "View", props: { bg: "$surfaceAlt", h: 10, w: "82%", br: "$2" }, children: [] },
    "home-skeleton-3": { id: "home-skeleton-3", parentId: "home-skeleton", type: "View", props: { bg: "$surfaceAlt", h: 10, w: "40%", br: "$2" }, children: [] },
    "home-empty": { id: "home-empty", parentId: "home-root", type: "View", props: { bg: "$surface", borderColor: "$borderSubtle", borderWidth: 1, br: "$3", p: "$5" }, children: ["home-empty-stack"] },
    "home-empty-stack": { id: "home-empty-stack", parentId: "home-empty", type: "YStack", props: { ai: "center", gap: "$2" }, children: ["home-empty-icon", "home-empty-copy"] },
    "home-empty-icon": { id: "home-empty-icon", parentId: "home-empty-stack", type: "Icon", props: { icon: "user", tone: "muted", size: "2xl" }, children: [] },
    "home-empty-copy": { id: "home-empty-copy", parentId: "home-empty-stack", type: "Body", props: { text: "No workspace items yet.", color: "$textMuted" }, children: [] },
    "home-status": { id: "home-status", parentId: "home-root", type: "View", props: { bg: "$warningMuted", borderColor: "$warning", borderWidth: 1, br: "$3", p: "$3" }, children: ["home-status-copy"] },
    "home-status-copy": { id: "home-status-copy", parentId: "home-status", type: "Body", props: { text: "Session refresh failed. Retry from the toolbar.", color: "$warning" }, children: [] },
  },
};

const profileForm: UiDocument = {
  id: "profile-form",
  name: "Profile Form",
  description: "Editable account card inspired by the example app settings flow.",
  rootId: "profile-root",
  stateLayouts: {
    data: ["profile-header", "profile-fields", "profile-actions"],
    loading: ["profile-header", "profile-skeleton"],
    empty: ["profile-header", "profile-empty", "profile-actions"],
    error: ["profile-header", "profile-status", "profile-fields", "profile-actions"],
  },
  nodes: {
    "profile-root": { id: "profile-root", type: "YStack", props: { gap: "$3", bg: "$bg", p: "$3" }, children: ["profile-header", "profile-fields", "profile-actions"] },
    "profile-header": { id: "profile-header", parentId: "profile-root", type: "View", props: { bg: "$surfaceStrong", borderColor: "$borderSubtle", borderWidth: 1, br: "$3", p: "$4" }, children: ["profile-header-stack"] },
    "profile-header-stack": { id: "profile-header-stack", parentId: "profile-header", type: "YStack", props: { gap: "$1" }, children: ["profile-label", "profile-title", "profile-body"] },
    "profile-label": { id: "profile-label", parentId: "profile-header-stack", type: "Label", props: { text: "profile", color: "$textMuted", tt: "uppercase", letterSpacing: 1 }, children: [] },
    "profile-title": { id: "profile-title", parentId: "profile-header-stack", type: "Heading", props: { text: "Edit your identity" }, children: [] },
    "profile-body": { id: "profile-body", parentId: "profile-header-stack", type: "Body", props: { text: "Draft state flows directly into reusable settings surfaces.", color: "$textMuted" }, children: [] },
    "profile-fields": { id: "profile-fields", parentId: "profile-root", type: "View", props: { bg: "$surface", borderColor: "$borderSubtle", borderWidth: 1, br: "$3", p: "$4" }, children: ["profile-fields-stack"] },
    "profile-fields-stack": { id: "profile-fields-stack", parentId: "profile-fields", type: "YStack", props: { gap: "$3" }, children: ["profile-name", "profile-handle"] },
    "profile-name": { id: "profile-name", parentId: "profile-fields-stack", type: "YStack", props: { gap: "$1" }, children: ["profile-name-label", "profile-name-input"] },
    "profile-name-label": { id: "profile-name-label", parentId: "profile-name", type: "Body", props: { text: "Display name", color: "$textMuted", fontSize: "$1" }, children: [] },
    "profile-name-input": { id: "profile-name-input", parentId: "profile-name", type: "View", props: { bg: "$surfaceAlt", borderColor: "$border", borderWidth: 1, br: "$2", px: "$3", py: "$2" }, children: ["profile-name-copy"] },
    "profile-name-copy": { id: "profile-name-copy", parentId: "profile-name-input", type: "Body", props: { text: "Taylor Example", color: "$textPrimary" }, children: [] },
    "profile-handle": { id: "profile-handle", parentId: "profile-fields-stack", type: "YStack", props: { gap: "$1" }, children: ["profile-handle-label", "profile-handle-input"] },
    "profile-handle-label": { id: "profile-handle-label", parentId: "profile-handle", type: "Body", props: { text: "Public handle", color: "$textMuted", fontSize: "$1" }, children: [] },
    "profile-handle-input": { id: "profile-handle-input", parentId: "profile-handle", type: "View", props: { bg: "$surfaceAlt", borderColor: "$border", borderWidth: 1, br: "$2", px: "$3", py: "$2" }, children: ["profile-handle-copy"] },
    "profile-handle-copy": { id: "profile-handle-copy", parentId: "profile-handle-input", type: "Body", props: { text: "@example", color: "$textPrimary" }, children: [] },
    "profile-actions": { id: "profile-actions", parentId: "profile-root", type: "XStack", props: { gap: "$3" }, children: ["profile-save", "profile-cancel"] },
    "profile-save": { id: "profile-save", parentId: "profile-actions", type: "Button", props: { text: "Save profile", bg: "$primary" }, children: [] },
    "profile-cancel": { id: "profile-cancel", parentId: "profile-actions", type: "Button", props: { text: "Cancel", bg: "$surfaceAlt", borderColor: "$border", borderWidth: 1 }, children: [] },
    "profile-skeleton": { id: "profile-skeleton", parentId: "profile-root", type: "YStack", props: { gap: "$2", bg: "$surface", borderColor: "$borderSubtle", borderWidth: 1, br: "$3", p: "$3" }, children: ["profile-skeleton-1", "profile-skeleton-2", "profile-skeleton-3"] },
    "profile-skeleton-1": { id: "profile-skeleton-1", parentId: "profile-skeleton", type: "View", props: { bg: "$surfaceAlt", h: 14, w: "56%", br: "$2" }, children: [] },
    "profile-skeleton-2": { id: "profile-skeleton-2", parentId: "profile-skeleton", type: "View", props: { bg: "$surfaceAlt", h: 10, w: "82%", br: "$2" }, children: [] },
    "profile-skeleton-3": { id: "profile-skeleton-3", parentId: "profile-skeleton", type: "View", props: { bg: "$surfaceAlt", h: 10, w: "40%", br: "$2" }, children: [] },
    "profile-empty": { id: "profile-empty", parentId: "profile-root", type: "View", props: { bg: "$surface", borderColor: "$borderSubtle", borderWidth: 1, br: "$3", p: "$5" }, children: ["profile-empty-stack"] },
    "profile-empty-stack": { id: "profile-empty-stack", parentId: "profile-empty", type: "YStack", props: { ai: "center", gap: "$2" }, children: ["profile-empty-icon", "profile-empty-copy"] },
    "profile-empty-icon": { id: "profile-empty-icon", parentId: "profile-empty-stack", type: "Icon", props: { icon: "user", tone: "muted", size: "2xl" }, children: [] },
    "profile-empty-copy": { id: "profile-empty-copy", parentId: "profile-empty-stack", type: "Body", props: { text: "No profile data yet.", color: "$textMuted" }, children: [] },
    "profile-status": { id: "profile-status", parentId: "profile-root", type: "View", props: { bg: "$errorMuted", borderColor: "$error", borderWidth: 1, br: "$3", p: "$3" }, children: ["profile-status-copy"] },
    "profile-status-copy": { id: "profile-status-copy", parentId: "profile-status", type: "Body", props: { text: "Save failed. Retry after reconnecting.", color: "$error" }, children: [] },
  },
};

const onboardingPanel: UiDocument = {
  id: "onboarding-panel",
  name: "Onboarding Panel",
  description: "Question flow composition for the scaffolded onboarding feature.",
  rootId: "onboarding-root",
  stateLayouts: {
    data: ["onboarding-header", "onboarding-chips", "onboarding-action"],
    loading: ["onboarding-header", "onboarding-skeleton"],
    empty: ["onboarding-header", "onboarding-empty", "onboarding-action"],
    error: ["onboarding-header", "onboarding-status", "onboarding-action"],
  },
  nodes: {
    "onboarding-root": { id: "onboarding-root", type: "YStack", props: { gap: "$3", bg: "$bg", p: "$3" }, children: ["onboarding-header", "onboarding-chips", "onboarding-action"] },
    "onboarding-header": { id: "onboarding-header", parentId: "onboarding-root", type: "View", props: { bg: "$surfaceStrong", borderColor: "$borderSubtle", borderWidth: 1, br: "$3", p: "$4" }, children: ["onboarding-header-stack"] },
    "onboarding-header-stack": { id: "onboarding-header-stack", parentId: "onboarding-header", type: "YStack", props: { gap: "$1" }, children: ["onboarding-label", "onboarding-title", "onboarding-body"] },
    "onboarding-label": { id: "onboarding-label", parentId: "onboarding-header-stack", type: "Label", props: { text: "flow", color: "$textMuted", tt: "uppercase", letterSpacing: 1 }, children: [] },
    "onboarding-title": { id: "onboarding-title", parentId: "onboarding-header-stack", type: "Heading", props: { text: "Finish setup" }, children: [] },
    "onboarding-body": { id: "onboarding-body", parentId: "onboarding-header-stack", type: "Body", props: { text: "Questions, chips, and save gating all sit in one scaffolded screen.", color: "$textMuted" }, children: [] },
    "onboarding-chips": { id: "onboarding-chips", parentId: "onboarding-root", type: "View", props: { bg: "$surface", borderColor: "$borderSubtle", borderWidth: 1, br: "$3", p: "$4" }, children: ["onboarding-chip-stack"] },
    "onboarding-chip-stack": { id: "onboarding-chip-stack", parentId: "onboarding-chips", type: "YStack", props: { gap: "$3" }, children: ["onboarding-question", "onboarding-options"] },
    "onboarding-question": { id: "onboarding-question", parentId: "onboarding-chip-stack", type: "Heading", props: { text: "What are you building?", fontSize: "$5" }, children: [] },
    "onboarding-options": { id: "onboarding-options", parentId: "onboarding-chip-stack", type: "XStack", props: { gap: "$2", ai: "center" }, children: ["onboarding-opt-1", "onboarding-opt-2", "onboarding-opt-3"] },
    "onboarding-opt-1": { id: "onboarding-opt-1", parentId: "onboarding-options", type: "Tag", props: { label: "iOS app", tone: "info" }, children: [] },
    "onboarding-opt-2": { id: "onboarding-opt-2", parentId: "onboarding-options", type: "Tag", props: { label: "Admin tool", tone: "muted" }, children: [] },
    "onboarding-opt-3": { id: "onboarding-opt-3", parentId: "onboarding-options", type: "Tag", props: { label: "Desktop app", tone: "muted" }, children: [] },
    "onboarding-action": { id: "onboarding-action", parentId: "onboarding-root", type: "Button", props: { text: "Continue", bg: "$primary" }, children: [] },
    "onboarding-skeleton": { id: "onboarding-skeleton", parentId: "onboarding-root", type: "YStack", props: { gap: "$2", bg: "$surface", borderColor: "$borderSubtle", borderWidth: 1, br: "$3", p: "$3" }, children: ["onboarding-skeleton-1", "onboarding-skeleton-2", "onboarding-skeleton-3"] },
    "onboarding-skeleton-1": { id: "onboarding-skeleton-1", parentId: "onboarding-skeleton", type: "View", props: { bg: "$surfaceAlt", h: 14, w: "56%", br: "$2" }, children: [] },
    "onboarding-skeleton-2": { id: "onboarding-skeleton-2", parentId: "onboarding-skeleton", type: "View", props: { bg: "$surfaceAlt", h: 10, w: "82%", br: "$2" }, children: [] },
    "onboarding-skeleton-3": { id: "onboarding-skeleton-3", parentId: "onboarding-skeleton", type: "View", props: { bg: "$surfaceAlt", h: 10, w: "40%", br: "$2" }, children: [] },
    "onboarding-empty": { id: "onboarding-empty", parentId: "onboarding-root", type: "View", props: { bg: "$surface", borderColor: "$borderSubtle", borderWidth: 1, br: "$3", p: "$5" }, children: ["onboarding-empty-stack"] },
    "onboarding-empty-stack": { id: "onboarding-empty-stack", parentId: "onboarding-empty", type: "YStack", props: { ai: "center", gap: "$2" }, children: ["onboarding-empty-icon", "onboarding-empty-copy"] },
    "onboarding-empty-icon": { id: "onboarding-empty-icon", parentId: "onboarding-empty-stack", type: "Icon", props: { icon: "table", tone: "muted", size: "2xl" }, children: [] },
    "onboarding-empty-copy": { id: "onboarding-empty-copy", parentId: "onboarding-empty-stack", type: "Body", props: { text: "No onboarding content to render.", color: "$textMuted" }, children: [] },
    "onboarding-status": { id: "onboarding-status", parentId: "onboarding-root", type: "View", props: { bg: "$warningMuted", borderColor: "$warning", borderWidth: 1, br: "$3", p: "$3" }, children: ["onboarding-status-copy"] },
    "onboarding-status-copy": { id: "onboarding-status-copy", parentId: "onboarding-status", type: "Body", props: { text: "Flow unavailable right now. Reload the contract.", color: "$warning" }, children: [] },
  },
};

export const UI_PLAYGROUND_DOCUMENTS: UiDocument[] = [
  homeSurface,
  profileForm,
  onboardingPanel,
];
