import type { ButtonContract } from "../../components/button/button.styles";
import type { PressableContract } from "../../components/pressable/pressable.styles";
import type { ListItemContract } from "../../components/list-item/list-item.styles";
import type { ChipContract } from "../../components/chip/chip.styles";
import type { TabContract } from "../../components/tab/tab.styles";
import type { IconButtonContract } from "../../components/icon-button/icon-button.styles";
import type { CardContract } from "../../components/card/card.styles";
import type { CardListContract } from "../../components/card-list/card-list.styles";
import type { MenuItemContract } from "../../components/menu-item/menu-item.styles";
import type { BadgeContract } from "../../components/badge/badge.styles";
import type { TagContract } from "../../components/tag/tag.styles";
import type { InputContract } from "../../components/input/input.styles";
import type { AvatarContract } from "../../components/avatar/avatar.styles";
import type { ProgressBarContract } from "../../components/progress-bar/progress-bar.styles";
import type { ImageContract, TableContract } from "../../components/table/table.styles";
import type { SelectableChipContract } from "../../components/selectable-chip/selectable-chip.styles";
import type { TextAreaContract } from "../../components/text-area/text-area.styles";
import type { SelectContract } from "../../components/select/select.styles";
import type { MultiSelectContract } from "../../components/multi-select/multi-select.styles";
import type { TabsContract } from "../../components/tabs/tabs.styles";
import type { SizingToolbarContract } from "../../components/sizing-toolbar/sizing-toolbar.styles";
import type { TabbedPanelContract } from "../../components/tabbed-panel/tabbed-panel.styles";
import type { DockPanelContract } from "../../components/dock-panel/dock-panel.styles";
import type { DockSplitterContract } from "../../components/dock-splitter/dock-splitter.styles";
import type { ColorPalettePickerContract } from "../../components/color-palette-picker/color-palette-picker.styles";

export interface PrimitiveContracts {
  button?: Record<string, ButtonContract>;
  pressable?: Record<string, PressableContract>;
  listItem?: Record<string, ListItemContract>;
  chip?: Record<string, ChipContract>;
  tab?: Record<string, TabContract>;
  iconButton?: Record<string, IconButtonContract>;
  card?: Record<string, CardContract>;
  cardList?: Record<string, CardListContract>;
  menuItem?: Record<string, MenuItemContract>;
  badge?: Record<string, BadgeContract>;
  tag?: Record<string, TagContract>;
  input?: Record<string, InputContract>;
  avatar?: Record<string, AvatarContract>;
  progressBar?: Record<string, ProgressBarContract>;
  image?: Record<string, ImageContract>;
  table?: Record<string, TableContract>;
  selectableChip?: Record<string, SelectableChipContract>;
  textArea?: Record<string, TextAreaContract>;
  select?: Record<string, SelectContract>;
  multiSelect?: Record<string, MultiSelectContract>;
  tabs?: Record<string, TabsContract>;
  sizingToolbar?: Record<string, SizingToolbarContract>;
  tabbedPanel?: Record<string, TabbedPanelContract>;
  dockPanel?: Record<string, DockPanelContract>;
  dockSplitter?: Record<string, DockSplitterContract>;
  colorPalettePicker?: Record<string, ColorPalettePickerContract>;
}
